services:
  - type: web
    name: check-print-api
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: checkprint-db
          property: connectionURI
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.6
